[project]
name = "database-integration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.3",
    "sqlalchemy[asyncio]>=2.0.44",
]
